# Generated by Django 3.2.13 on 2022-08-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feature_featurecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecategory',
            name='rank',
            field=models.PositiveSmallIntegerField(default=999, verbose_name='display order'),
        ),
    ]
