# Generated by Django 3.2.13 on 2022-08-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_featurecategory_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
    ]
