# Generated by Django 3.2.13 on 2022-08-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220810_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, related_name='features', to='core.Feature', verbose_name='features'),
        ),
    ]
