# Generated by Django 3.2.13 on 2022-08-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features', to='core.Feature', verbose_name='features'),
        ),
    ]
