# Generated by Django 3.2.13 on 2022-08-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='scope',
            field=models.PositiveSmallIntegerField(choices=[(1, 'only on mission description'), (2, 'only on entrepreneur profile'), (3, 'on both mission & profile')], default=3, verbose_name='scope'),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='scope',
            field=models.PositiveSmallIntegerField(choices=[(1, 'only on mission description'), (2, 'only on entrepreneur profile'), (3, 'on both mission & profile')], default=3, verbose_name='scope'),
        ),
    ]
