# Generated by Django 3.2.13 on 2022-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220812_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='scope',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Only on mission description'), (2, 'Only on entrepreneur profile'), (3, 'On both mission & profile')], default=3, verbose_name='scope'),
        ),
        migrations.AlterField(
            model_name='featurecategory',
            name='scope',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Only on mission description'), (2, 'Only on entrepreneur profile'), (3, 'On both mission & profile')], default=3, verbose_name='scope'),
        ),
    ]
