# Generated by Django 3.2.13 on 2022-08-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220812_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ('start',), 'verbose_name': 'Availability timeslot', 'verbose_name_plural': 'Availability timeslots'},
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='to_dt',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='from_dt',
            new_name='start',
        ),
    ]
