# Generated by Django 3.2.13 on 2022-08-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220812_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklocation',
            name='latitude',
            field=models.FloatField(blank=True, default=None, editable=False, help_text='this field is autocompleted', null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='longitude',
            field=models.FloatField(blank=True, default=None, editable=False, help_text='this field is autocompleted', null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='worklocation',
            name='city',
            field=models.CharField(blank=True, default=None, editable=False, help_text='this field is auto-completed', max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='worklocation',
            name='department',
            field=models.PositiveIntegerField(blank=True, default=None, editable=False, help_text='this field is autocompleted', null=True, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='worklocation',
            name='department_name',
            field=models.CharField(blank=True, default=None, editable=False, help_text='this field is autocompleted', max_length=100, null=True, verbose_name='department name'),
        ),
        migrations.AlterField(
            model_name='worklocation',
            name='region',
            field=models.CharField(blank=True, default=None, editable=False, help_text='this field is autocompleted', max_length=100, null=True, verbose_name='region'),
        ),
    ]
