# Generated by Django 3.2.13 on 2022-08-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220812_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.Feature', verbose_name='features'),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('start', models.DateField(verbose_name='start date')),
                ('end', models.DateField(verbose_name='end date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='core.company', verbose_name='company')),
                ('features', models.ManyToManyField(blank=True, related_name='missions', to='core.Feature', verbose_name='features')),
            ],
            options={
                'verbose_name': 'mission',
                'verbose_name_plural': 'missions',
            },
        ),
    ]
