# Generated by Django 3.2.13 on 2022-08-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220819_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='city',
            field=models.CharField(blank=True, default=None, editable=False, help_text='this field is auto-completed', max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='mission',
            name='zipcode',
            field=models.CharField(max_length=5, verbose_name='zipcode'),
            preserve_default=False,
        ),
    ]
