# Generated by Django 3.2.13 on 2022-08-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220819_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driving_license',
            field=models.BooleanField(default=False),
        ),
    ]
