# Generated by Django 3.2.13 on 2022-08-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_driving_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='driving_license_required',
            field=models.BooleanField(default=False, verbose_name='driving license required'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driving_license',
            field=models.BooleanField(default=False, verbose_name='driving license'),
        ),
    ]
