# Generated by Django 3.2.13 on 2022-08-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_mission_is_matchable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='is_matchable',
            field=models.BooleanField(default=True, verbose_name='is matchable'),
        ),
    ]
