# Generated by Django 3.2.13 on 2022-08-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_mission_is_matchable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='required for company users and entrepreneur', max_length=20, null=True, verbose_name='phone number'),
        ),
    ]
