# Generated by Django 3.2.13 on 2022-08-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0606060606', help_text='required for company users and entrepreneur', max_length=20, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
