# Generated by Django 3.2.13 on 2022-08-26 12:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20220826_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='files',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/fichier'), upload_to=''),
        ),
    ]
