# Generated by Django 3.2.13 on 2022-08-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_user_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='files',
            field=models.FileField(blank=True, upload_to='', verbose_name='files required'),
        ),
    ]
