# Generated by Django 3.2.13 on 2022-08-29 18:55

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_user_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='Pas de description', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='files',
            field=models.FileField(blank=True, upload_to=core.models.user.User.group_based_upload_to, verbose_name='files required'),
        ),
    ]
